# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # Ignore any update that is a patch release.
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    labels:
      - "Dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"
