name: "Format"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  ruff:
    name: "Format with Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: actions/checkout@v5

        - name: "Set up Python"
          uses: actions/setup-python@v6
          with:
            python-version: "3.12"
            cache: "pip"

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: "Run Ruff formatting check"
          run: |
            ruff format . --check