name: "Lint"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  ruff:
    name: "Linting with Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: actions/checkout@v5

        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"
            cache: "pip"

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: "Run Ruff linting check"
          run: |
            ruff check . --output-format=github