name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

env:
  PYTHON_VERSION: "3.12"

jobs:
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v5"

      - name: Setup Python
        uses: "actions/setup-python@v5"
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pytest requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-md pytest-emoji

      - name: Run tests
        uses: pavelzw/pytest-action@v2
        with:
          click-to-expand: false